#!/bin/bash

# ~/ubuntu

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `ubuntu` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

sudo apt update

# Essentials
sudo apt install -y openssh-server net-tools curl git vim trash-cli tmux xclip

# Dev tools
sudo apt install -y fzf ripgrep fd-find exa
